language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "florianguigue-github"
    token:
      secure: travis encrypt "token"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - 'C:/Utilisateurs/A643564/.m2/repository'
    - 'C:/Utilisateurs/A643564/.sonar/cache'
