language: java
cache:
  directories:
    - 'C:/Utilisateurs/A643564/.m2/repository'
    - 'C:/Utilisateurs/A643564/.sonar/cache'

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean install


