language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "florianguigue-github"
    token:
      secure: "b3553bf1d2cf0047f4880abd0beda3de9c3fd6ff"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login="b3553bf1d2cf0047f4880abd0beda3de9c3fd6ff"

cache:
  directories:
    - 'C:/Utilisateurs/A643564/.m2/repository'
    - 'C:/Utilisateurs/A643564/.sonar/cache'
